'use client'
import { useState } from 'react'
import { ChevronDown } from 'lucide-react'
import Link from 'next/link'
import { ContactBookingFlow } from '@/components/contact-booking-flow'

const faqs=[
 {q:'How fast will I hear back?',a:'Within one business day — usually much sooner. We reply personally, no auto-sequence.'},
 {q:"What if I'm not ready to buy yet?",a:"Totally fine. The discovery call is free and honest — if automation isn't the right fit yet, we'll tell you."},
 {q:'Do you work with businesses outside the US?',a:"We focus on US small businesses so we can match local hours, tools, and compliance — but reach out and we'll let you know if we can help."}
]

export function ContactPageClient(){
 const [open,setOpen]=useState(-1)

 return <div className="contact-approved">
 <section className="con-hero"><i className="con-blob"/><div><div className="con-grid"> <div className="con-copy"><div className="con-badge"><i/>Let&apos;s talk</div><h1>Tell us what&apos;s eating your team&apos;s time.</h1><p>Two quick steps: tell us about your workflow, then pick a 30-minute discovery call that suits you. After the call you&apos;ll get a fixed quote and timeline.</p><div className="con-next"><strong>What happens next</strong>{['Tell us about your workflow — takes under a minute.','Pick a 30-minute slot — we map your biggest time drains on the call.','You get a fixed quote and timeline — no pressure to commit.'].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div><div className="con-chips">{['Free audit included','No long contracts','30-day support'].map(x=><span key={x}><b>✓</b>{x}</span>)}</div></div>
 <div className="con-form-card"><ContactBookingFlow /></div></div></div></section>
 {/* D-C2: Portal target for step-2 booking section — rendered outside hero */}
 <div id="contact-booking-portal" />
 <section className="con-reach"><div><strong>Other ways to reach us</strong><div><a href="mailto:hello@codeoutfitters.ai"><i><img src="/assets/icon-edit-square.svg" alt=""/></i><span><b>Email us</b><small>hello@codeoutfitters.ai</small></span></a><a href="https://wa.me/15550123456"><i><img src="/assets/icon-chat-square.svg" alt=""/></i><span><b>WhatsApp</b><small>Chat with our own bot</small></span></a><Link href="/process"><i><img src="/assets/icon-scale.svg" alt=""/></i><span><b>See our process</b><small>How discovery leads to a fixed quote</small></span></Link></div></div></section>
 <section className="con-faq"><div><header><div><i/>Before you write in<i/></div><h2>Quick answers first.</h2></header><div>{faqs.map((x,i)=>{const active=open===i;const panelId=`con-faq-panel-${i}`;const btnId=`con-faq-btn-${i}`;return <article className={active?'open':''} key={x.q}><button id={btnId} aria-expanded={active} aria-controls={panelId} onClick={()=>setOpen(active?-1:i)}><span>{x.q}</span><i><ChevronDown size={17}/></i></button><div className="con-answer" id={panelId} role="region" aria-labelledby={btnId}><div><p>{x.a}</p></div></div></article>})}</div></div></section>
 <style>{`
 .contact-approved,.contact-approved *{box-sizing:border-box}.contact-approved{overflow:hidden}.con-hero{position:relative;background:radial-gradient(1000px 600px at 78% -15%,rgba(23,160,99,.2),transparent 60%),radial-gradient(700px 460px at 2% 115%,rgba(217,179,106,.09),transparent 60%),#0A120E}.con-blob{position:absolute;inset:-20%;background:radial-gradient(560px 380px at 26% 36%,rgba(43,212,131,.1),transparent 60%),radial-gradient(520px 360px at 76% 66%,rgba(217,179,106,.08),transparent 60%);animation:conBlob 16s ease-in-out infinite;pointer-events:none}.con-hero>div{position:relative;max-width:1180px;margin:auto;padding:clamp(56px,8vw,84px) clamp(20px,3vw,32px) clamp(64px,9vw,100px)}.con-grid{max-width:1100px;margin:auto;display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.05fr);gap:clamp(32px,4vw,64px);align-items:start}.con-copy{display:flex;flex-direction:column;gap:24px}.con-badge{align-self:flex-start;display:flex;align-items:center;gap:9px;padding:8px 16px;border-radius:999px;background:rgba(217,179,106,.1);border:1px solid rgba(217,179,106,.4);font:700 11.5px 'Instrument Sans';letter-spacing:.14em;color:#D9B36A;text-transform:uppercase;animation:v3Rise .65s var(--ease-premium) both}.con-badge i{width:7px;height:7px;border-radius:50%;background:#D9B36A}.con-copy h1{margin:0;font:600 clamp(32px,4.2vw,50px)/1.12 'Space Grotesk';color:#F5F0E8;letter-spacing:-.02em;animation:v3Rise .7s .08s var(--ease-premium) both}.con-copy>p{max-width:440px;margin:0;font:400 17.5px/1.65 'Instrument Sans';color:rgba(245,240,232,.62)}.con-next{display:flex;flex-direction:column;gap:16px;margin-top:8px}.con-next>strong{font:700 10.5px 'Instrument Sans';letter-spacing:.14em;color:rgba(245,240,232,.5);text-transform:uppercase}.con-next>span{display:flex;align-items:flex-start;gap:12px;font:500 15px/1.55 'Instrument Sans';color:rgba(245,240,232,.8)}.con-next>span b{width:26px;height:26px;display:flex;align-items:center;justify-content:center;flex-shrink:0;border-radius:50%;background:#EAF6EF;color:#128A54;font:700 12px 'Space Grotesk';animation:v3Pop .45s .5s var(--ease-premium) both}.con-chips{display:flex;flex-wrap:wrap;gap:10px;margin-top:8px}.con-chips>span{display:inline-flex;align-items:center;gap:6px;padding:7px 14px;border-radius:999px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.12);font:500 12.5px 'Instrument Sans';color:rgba(245,240,232,.72)}.con-chips b{color:#2BD483;font-weight:700}.con-form-card{padding:clamp(26px,3vw,34px);background:linear-gradient(178deg,#fff,#FBF7EE 68%,#F6F1E4);border:1px solid rgba(13,58,49,.14);border-radius:22px;box-shadow:0 34px 82px rgba(0,0,0,.4)}
 .con-reach{background:#0E241A}.con-reach>div{max-width:1180px;margin:auto;padding:clamp(48px,6vw,64px) clamp(20px,3vw,32px)}.con-reach>div>strong{display:block;margin-bottom:22px;text-align:center;font:700 11px 'Instrument Sans';letter-spacing:.18em;color:rgba(245,240,232,.5);text-transform:uppercase}.con-reach>div>div{max-width:840px;margin:auto;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.con-reach a{display:flex;align-items:center;gap:10px;padding:14px 16px;border-radius:14px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.12);text-decoration:none;transition:.3s}.con-reach a:hover{transform:translateY(-3px);background:rgba(255,255,255,.08)}.con-reach a>i{width:38px;height:38px;display:flex;align-items:center;justify-content:center;flex-shrink:0;border-radius:10px;background:rgba(23,160,99,.14)}.con-reach img{width:18px;height:18px}.con-reach a>span{display:flex;flex-direction:column;min-width:0}.con-reach a b{font:600 14px 'Instrument Sans';color:#F5F0E8}.con-reach a small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:400 12.5px 'Instrument Sans';color:rgba(245,240,232,.5)}
 .con-faq{background:#F7F2EA}.con-faq>div{max-width:700px;margin:auto;padding:clamp(56px,8vw,80px) clamp(20px,3vw,32px)}.con-faq header{display:flex;flex-direction:column;align-items:center;gap:14px;margin-bottom:36px;text-align:center}.con-faq header>div{display:flex;align-items:center;gap:14px;font:700 12px 'Instrument Sans';letter-spacing:.18em;color:#128A54;text-transform:uppercase}.con-faq header>div i{width:38px;height:2px;background:#D9B36A}.con-faq h2{margin:0;font:600 clamp(26px,3.2vw,36px)/1.15 'Space Grotesk';color:#0A120E}.con-faq>div>div{display:flex;flex-direction:column;gap:12px}.con-faq article{overflow:hidden;border-radius:16px;background:#FCFAF4;border:1px solid #EDE6D8}.con-faq article.open{background:#fff;border-color:rgba(23,160,99,.4);box-shadow:0 18px 40px rgba(18,32,27,.12)}.con-faq button{width:100%;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px 22px;border:0;background:transparent;text-align:left;font:600 16px 'Space Grotesk';color:#0A120E}.con-faq button i{width:30px;height:30px;display:flex;align-items:center;justify-content:center;flex-shrink:0;border-radius:50%;background:#EFE9DC;color:#128A54;transition:.35s}.con-faq .open button i{background:#128A54;color:#fff;transform:rotate(180deg)}.con-answer{display:grid;grid-template-rows:0fr;opacity:0;transition:.45s}.con-answer>div{overflow:hidden}.con-answer p{margin:0;padding:0 22px 20px;font:400 15px/1.62 'Instrument Sans';color:#68705F}.con-faq .open .con-answer{grid-template-rows:1fr;opacity:1}@media(max-width:900px){.con-grid{grid-template-columns:1fr}}@media(max-width:640px){.con-reach>div>div{grid-template-columns:1fr}}
 `}</style></div>}