'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'

const services=[['WhatsApp Automation','/services#whatsapp'],['Email Workflows','/services#email'],['AI Chatbots','/services#support'],['Booking Bots','/services#booking'],['Invoice Automation','/services#invoice'],['Custom Builds','/services#custom']]
const company=[['Home','/'],['About','/about'],['Industries','/industries'],['Process','/process'],['Case Studies','/case-studies'],['Security & Reliability','/security'],['Contact','/contact']]

export function Footer(){
 const pathname=usePathname();const visibleCompany=pathname==='/'?company.slice(1):company
 return <footer className="site-footer"><div className="site-footer-main"><div className="site-footer-brand"><div><img src="/assets/logo-mark.svg" alt=""/><span>Code<b>Outfitters</b></span></div><p>AI automation for US small businesses. We eliminate repetitive work so you can focus on what actually grows your business.</p></div><div><strong>Services</strong>{services.map(([label,href])=><Link href={href} key={label}>{label}</Link>)}</div><div><strong>Company</strong>{visibleCompany.map(([label,href])=><Link href={href} key={label}>{label}</Link>)}</div></div><div className="site-footer-lower"><span>© 2026 CodeOutfitters LLC. All rights reserved.</span><span><i/>All systems operational</span></div><style>{`
 .site-footer{background:#070D0A;border-top:1px solid rgba(255,255,255,.06)}.site-footer-main{max-width:1180px;margin:0 auto;display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:40px;padding:56px 32px 40px}.site-footer-main>div{display:flex;flex-direction:column;gap:12px}.site-footer-brand>div{display:flex;align-items:center;gap:9px}.site-footer-brand img{width:24px;height:24px}.site-footer-brand span{font:600 17px 'Space Grotesk',sans-serif;color:#F5F0E8}.site-footer-brand b{color:#2BD483}.site-footer-brand p{margin:0;font:400 15px/1.65 'Instrument Sans',sans-serif;color:rgba(245,240,232,.45);max-width:300px}.site-footer-main strong{font:700 11.5px 'Instrument Sans',sans-serif;letter-spacing:.16em;color:rgba(245,240,232,.4);text-transform:uppercase}.site-footer-main a{font:500 14.5px 'Instrument Sans',sans-serif;color:rgba(245,240,232,.6);text-decoration:none}.site-footer-main a:hover{color:#F5F0E8}.site-footer-lower{max-width:1180px;margin:0 auto;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px;padding:20px 32px;border-top:1px solid rgba(255,255,255,.06);font:400 12.5px 'Instrument Sans',sans-serif;color:rgba(245,240,232,.35)}.site-footer-lower span+span{display:flex;align-items:center;gap:7px;color:rgba(245,240,232,.5)}.site-footer-lower i{width:7px;height:7px;border-radius:50%;background:#2BD483}@media(max-width:560px){.site-footer-main{padding:46px 20px 34px;grid-template-columns:1fr}.site-footer-lower{padding:18px 20px;align-items:flex-start;flex-direction:column}}
 `}</style></footer>
}
