'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'

const links=[['Services','/services'],['Industries','/industries'],['Process','/process'],['Case Studies','/case-studies'],['About','/about']]

export function Navbar(){
 const pathname=usePathname()
 return <>{pathname==='/'&&<div className="site-announcement">Free workflow audit with every discovery call this July. <a href="#cta">Book yours →</a></div>}<nav className="site-navbar"><div><Link href="/" className="site-logo"><img src="/assets/logo-mark.svg" alt=""/><span>Code<b>Outfitters</b></span></Link><div className="site-links">{links.map(([label,href])=>pathname===href?<span key={href}>{label}</span>:<Link key={href} href={href}>{label}</Link>)}</div>{pathname==='/contact'?<span className="site-nav-current">Contact</span>:<Link className="site-nav-cta" href="/contact">Book a Call</Link>}</div></nav><style>{`
 .site-announcement{background:#0E2A1D;padding:10px 16px;text-align:center;font:500 13.5px/1.5 'Instrument Sans',sans-serif;color:rgba(245,240,232,.85)}.site-announcement a{font-weight:700;color:#D9B36A;text-decoration:underline;text-underline-offset:3px;white-space:nowrap}.site-navbar{position:sticky;top:0;z-index:50;background:rgba(247,242,234,.92);backdrop-filter:blur(14px);border-bottom:1px solid #E5DCCB}.site-navbar>div{max-width:1180px;min-height:68px;margin:0 auto;padding:10px clamp(16px,3vw,32px);display:flex;align-items:center;justify-content:space-between;gap:14px}.site-logo{display:flex;align-items:center;gap:10px;text-decoration:none;white-space:nowrap;flex-shrink:0}.site-logo img{width:28px;height:28px}.site-logo span{font:600 19px 'Space Grotesk',sans-serif;color:#0A120E;letter-spacing:-.01em}.site-logo b{color:#17A063}.site-links{display:flex;align-items:center;gap:clamp(14px,2vw,28px)}.site-links a,.site-links span{white-space:nowrap;font:500 15px 'Instrument Sans',sans-serif;color:#4A5248;text-decoration:none}.site-links span{font-weight:600;color:#128A54}.site-nav-current{font:600 14px 'Instrument Sans',sans-serif;color:#128A54;background:#EAF6EF;border:1px solid rgba(18,138,84,.25);border-radius:10px;padding:11px 18px;white-space:nowrap}.site-nav-cta{font:600 14px 'Instrument Sans',sans-serif;color:#F7F2EA;background:#0E2A1D;border-radius:10px;padding:11px 18px;white-space:nowrap;text-decoration:none;transition:.15s}.site-nav-cta:hover{color:#F7F2EA;background:#17A063;transform:translateY(-1px)}@media(max-width:960px){.site-links{display:none}}@media(max-width:420px){.site-announcement{font-size:12px;padding:8px 10px}.site-navbar>div{min-height:60px;padding-top:8px;padding-bottom:8px}.site-logo span{font-size:17px}.site-logo img{width:25px;height:25px}.site-nav-cta,.site-nav-current{font-size:12.5px;padding:9px 13px}}
 `}</style></>
}
