'use client'
import { useEffect,useState } from 'react'
import { useMotionMode } from '@/components/motion-mode-provider'

const stories=[
 {initials:'MR',color:'#17A063',name:'Marcus R.',role:'Owner, real estate agency',quote:'Leads used to sit unanswered overnight. Now the bot books viewings while I sleep — we doubled our response rate in the first month.'},
 {initials:'SK',color:'#D9B36A',name:'Sarah K.',role:'Founder, e-commerce brand',quote:'Invoicing went from 4 hours a day to 8 minutes. I genuinely forgot invoices were ever a problem.'},
 {initials:'DP',color:'#4457C7',name:'Dr. Patel',role:'Clinic director',quote:'Our front desk stopped drowning in scheduling calls. No-shows dropped 40% from the automated reminders alone.'},
 {initials:'JL',color:'#B4552F',name:'James L.',role:'Managing partner, law firm',quote:'Client intake used to take a paralegal half her week. The intake bot does it in minutes, and nothing falls through the cracks.'},
 {initials:'AT',color:'#8B4F9E',name:'Ana T.',role:'Operations lead, logistics co.',quote:'They mapped our whole dispatch workflow in one call and shipped the automation in six days. Easily paid for itself the first month.'},
 {initials:'BW',color:'#0E7490',name:'Ben W.',role:'Owner, HVAC services',quote:'The WhatsApp bot quotes jobs, books techs, and chases reviews. My phone finally stopped ringing at dinner.'},
]
function Card({s}:{s:typeof stories[number]}){return <article className="hp-tm-card"><div><b>"</b><span>★★★★★</span></div><p>{s.quote}</p><footer><i style={{background:s.color}}>{s.initials}</i><span><b>{s.name}</b><small>{s.role}</small></span></footer></article>}
function TmRow({reverse,dataMarquee}:{reverse?:boolean;dataMarquee?:string}){const list=reverse?[...stories].reverse():stories;return <div className={`hp-tm-row ${reverse?'is-reverse':''}`} data-marquee-track data-marquee={dataMarquee}><div data-marquee-sequence="original">{list.map(s=><Card s={s} key={s.name}/>)}</div><div data-marquee-sequence="duplicate" aria-hidden="true">{list.map(s=><Card s={s} key={`d-${s.name}`}/>)}</div></div>}
export function Testimonials(){
 const [current,setCurrent]=useState(0); const {reduced}=useMotionMode(); const [paused,setPaused]=useState(false)
 useEffect(()=>{if(reduced)return;const id=setInterval(()=>setCurrent(x=>(x+1)%3),6000);return()=>clearInterval(id)},[reduced])
 const s=stories[current]
 return <section className="hp-testimonials"><div className="hp-tm-inner"><header><div><i/>05 · Client love<i/></div><h2>Small teams. <span>Big time savings.</span></h2></header><article className="hp-featured"><small>★ Featured story</small><p>"{s.quote}"</p><footer><i style={{background:s.color}}>{s.initials}</i><span><b>{s.name}</b><small>{s.role}</small></span></footer><div>{stories.slice(0,3).map((_,i)=><button key={i} aria-label={`Story ${i+1}`} onClick={()=>setCurrent(i)} className={i===current?'is-active':''}/>)}</div></article></div><div className="hp-tm-marquee" data-marquee="home-client-love-testimonials" onPointerEnter={()=>setPaused(true)} onPointerLeave={()=>setPaused(false)}><TmRow dataMarquee="home-client-love-testimonials-row-1"/><TmRow reverse dataMarquee="home-client-love-testimonials-row-2"/></div><style>{`
 .hp-testimonials{position:relative;background:#0E241A;overflow:hidden}.hp-tm-inner{max-width:1180px;margin:0 auto;padding:clamp(56px,8vw,84px) clamp(20px,3vw,32px) 0}.hp-tm-inner>header{text-align:center;margin-bottom:38px}.hp-tm-inner>header>div{display:flex;align-items:center;justify-content:center;gap:14px;font:700 12px 'Instrument Sans',sans-serif;letter-spacing:.18em;color:#D9B36A;text-transform:uppercase}.hp-tm-inner>header>div i{width:38px;height:2px;background:rgba(217,179,106,.6)}.hp-tm-inner h2{margin:14px 0 0;font:600 clamp(32px,4.2vw,50px)/1.12 'Space Grotesk',sans-serif;color:#F5F0E8}.hp-tm-inner h2 span{color:#2BD483}.hp-featured{position:relative;max-width:740px;margin:0 auto 48px;background:linear-gradient(165deg,rgba(255,255,255,.06),rgba(255,255,255,.02));border:1px solid rgba(255,255,255,.14);border-radius:24px;padding:clamp(28px,4vw,44px);box-shadow:0 30px 70px rgba(0,0,0,.35);overflow:hidden}.hp-featured:before{content:'';position:absolute;top:-90px;left:50%;transform:translateX(-50%);width:280px;height:280px;border-radius:50%;background:radial-gradient(circle,rgba(43,212,131,.18),transparent 70%)}.hp-featured>small{position:relative;display:block;font:700 10.5px 'Instrument Sans',sans-serif;letter-spacing:.16em;color:#2BD483;text-transform:uppercase;margin-bottom:16px}.hp-featured>p{position:relative;margin:0 0 22px;font:500 clamp(19px,2.2vw,25px)/1.5 'Space Grotesk',sans-serif;color:#F5F0E8}.hp-featured footer,.hp-tm-card footer{position:relative;display:flex;align-items:center;gap:12px}.hp-featured footer>i{width:46px;height:46px}.hp-featured footer>i,.hp-tm-card footer>i{border-radius:50%;display:flex;align-items:center;justify-content:center;color:#fff;font:700 15px 'Space Grotesk',sans-serif;font-style:normal}.hp-featured footer>span,.hp-tm-card footer>span{display:flex;flex-direction:column}.hp-featured footer b{font:600 15px 'Instrument Sans',sans-serif;color:#F5F0E8}.hp-featured footer small{font:400 13px 'Instrument Sans',sans-serif;color:rgba(245,240,232,.5)}.hp-featured>div{display:flex;justify-content:center;gap:8px;margin-top:26px}.hp-featured button{width:8px;height:8px;border-radius:99px;border:0;background:rgba(255,255,255,.25);padding:0;transition:.3s;cursor:pointer}.hp-featured button.is-active{width:22px;background:#2BD483}
 .hp-tm-marquee{display:flex;flex-direction:column;gap:18px;padding:6px 0 clamp(56px,8vw,84px);mask-image:linear-gradient(90deg,transparent,#000 8%,#000 92%,transparent)}.hp-tm-row{display:flex;width:max-content;animation:hpTmL 52s linear infinite;will-change:transform}.hp-tm-row.is-reverse{animation:hpTmR 60s linear infinite}.hp-tm-row>div{display:flex;gap:18px;padding-right:18px}.hp-tm-marquee:hover .hp-tm-row{animation-play-state:paused}.hp-tm-card{width:min(400px,84vw);background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:24px 26px 22px;display:flex;flex-direction:column;gap:13px}.hp-tm-card>div{display:flex;align-items:flex-start;justify-content:space-between}.hp-tm-card>div b{font:700 46px Georgia,serif;line-height:.6;color:rgba(217,179,106,.45)}.hp-tm-card>div span{font:600 13px 'Instrument Sans',sans-serif;color:#D9B36A}.hp-tm-card>p{margin:0;font:400 15px/1.6 'Instrument Sans',sans-serif;color:rgba(245,240,232,.85)}.hp-tm-card footer{margin-top:auto;gap:11px}.hp-tm-card footer>i{width:40px;height:40px;font-size:14px}.hp-tm-card footer b{font:600 14px 'Instrument Sans',sans-serif;color:#F5F0E8}.hp-tm-card footer small{font:400 12.5px 'Instrument Sans',sans-serif;color:rgba(245,240,232,.5)}@keyframes hpTmL{to{transform:translateX(-50%)}}@keyframes hpTmR{from{transform:translateX(-50%)}to{transform:translateX(0)}}@media(max-width:640px){.hp-tm-card{width:min(300px,84vw);padding:18px 20px}}
 html[data-motion='reduced'] .hp-tm-row{animation:none}html[data-motion='reduced'] .hp-tm-row>div[data-marquee-sequence=duplicate]{display:none}@media(prefers-reduced-motion:reduce){html:not([data-motion='full']) .hp-tm-row{animation:none}html:not([data-motion='full']) .hp-tm-row>div[data-marquee-sequence=duplicate]{display:none}}
 `}</style></section>
}
