import type { OnboardingFormData, ProposalOutput } from './admin-types'

// Security 1 (2026-06-16): the frontend no longer holds the Anthropic API
// key. Proposals are generated by a Cloudflare Worker that holds the
// server-side `ANTHROPIC_API_KEY` secret. The frontend only knows the
// public Worker URL (`NEXT_PUBLIC_PROPOSAL_WORKER_URL`). The previous
// `NEXT_PUBLIC_ANTHROPIC_API_KEY` env var is deprecated and forbidden:
// do not reintroduce it.
const WORKER_URL = process.env.NEXT_PUBLIC_PROPOSAL_WORKER_URL ?? ''

export async function generateProposal(
  intakeData: OnboardingFormData
): Promise<ProposalOutput> {
  if (!WORKER_URL) {
    throw new Error(
      'Missing NEXT_PUBLIC_PROPOSAL_WORKER_URL — add it to your .env.local. See docs/SECURITY.md and repo-research/SECURITY_1_WORKER_PROXY_NOTES.md.'
    )
  }

  const endpoint = WORKER_URL.replace(/\/+$/, '') + '/'

  const res = await fetch(endpoint, {
    method: 'POST',
    credentials: 'omit',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ intakeData }),
  })

  if (!res.ok) {
    const body = await res.text()
    throw new Error(`Proposal service error (${res.status}): ${body}`)
  }

  const data = await res.json()
  return data as ProposalOutput
}
