'use client'
import { useState } from 'react'
import { ChevronDown, CircleHelp } from 'lucide-react'
import Link from 'next/link'
import { useScrollReveal } from '@/hooks/useScrollReveal'

const tools1=[['WhatsApp Business','whatsapp'],['Gmail','gmail'],['Outlook','outlook'],['QuickBooks','quickbooks'],['Stripe','stripe'],['Shopify','shopify'],['Calendly','calendly'],['Google Calendar','google-calendar'],['HubSpot','hubspot']]
const tools2=[['Zapier','zapier'],['Make','make'],['Slack','slack'],['Notion','notion'],['DocuSign','docusign'],['Twilio SMS','twilio'],['Airtable','airtable'],['Google Sheets','google-sheets'],['Zendesk','zendesk']]
const faqs=[
 {q:'Are you SOC 2 or HIPAA certified?',a:"No formal certifications today — we're upfront about that. We follow security-conscious practices (least-access setup, server-side secrets, human review for sensitive actions) on every build, and we'll tell you plainly if a requirement is outside what we currently support."},
 {q:'Who has access to our accounts and data?',a:'Only what the specific automation needs, connected with scoped or dedicated integration accounts wherever the platform supports it — not broad admin access by default.'},
 {q:'What happens if the AI gets something wrong?',a:'Sensitive actions (payments, cancellations, ambiguous requests) are routed to a human reviewer by design, not resolved automatically by the model.'},
 {q:'Can we review the system before it goes live?',a:'Yes — testing and review happen before launch, and you approve the build before it touches real customers or data.'},
 {q:'What if we need to pause or roll back an automation?',a:"Every handoff includes a documented rollback path, so pausing or reverting a system doesn't require guesswork."}
]
const access=[['Least-access setup','Every integration is connected with the minimum permissions needed to do its job — not broad, all-access keys by default. Access is easy to review, and easy to revoke.'],['Server-side secrets','API keys and credentials are kept server-side wherever the platform allows it, rather than exposed in client-facing code.'],['Scoped account access','We use dedicated integration accounts where possible, so access can be reviewed or revoked without touching your main tools.']]
const reliability=[['Monitoring mindset','We check in on live automations during the support window and flag anything behaving unexpectedly before it becomes your problem.'],['Documented handoff','Every project ends with documentation of what was built, how it works, and who to contact — not tribal knowledge.'],['Clear rollback plan','If something needs to be paused or reverted, that path is documented up front — not figured out under pressure. Every handoff includes the exact steps.']]
function ToolRow({items,reverse=false}:{items:string[][],reverse?:boolean}){const doubled=[...items,...items];return <div className={`sec-tool-row ${reverse?'reverse':''}`}>{doubled.map((t,i)=><span className="sec-tool" data-marquee-sequence={i<items.length?'original':'duplicate'} key={`${t[0]}-${i}`}><i><img src={`/assets/integrations/${t[1]}.svg`} alt={t[0]}/></i>{t[0]}</span>)}</div>}
export function SecurityPageClient(){const[open,setOpen]=useState(-1);const a=useScrollReveal<HTMLElement>(.08),g=useScrollReveal<HTMLElement>(.1),r=useScrollReveal<HTMLElement>(.08),m=useScrollReveal<HTMLElement>(.1),f=useScrollReveal<HTMLElement>(.08),c=useScrollReveal<HTMLElement>(.1);return <div className="security-approved">
 <section className="sec-hero"><div><div className="sec-badge"><i/>Security &amp; reliability</div><h1>Built with a <span>security-conscious</span> mindset.</h1><p>Automation touches sensitive parts of your business — your leads, your calendar, your money. Here&apos;s how we handle access, secrets, and reliability on every build.</p></div></section>
 <section className="sec-access" ref={a}><div><header data-reveal><div><i/>Access &amp; secrets<i/></div><h2>How we protect workflow access.</h2></header><div className="sec-grid">{access.map((x,i)=><article className={i===0?'feature':''} data-reveal key={x[0]}>{i===0?<div className="sec-feature"><h3>{x[0]}</h3><p>{x[1]}</p></div>:<><h3>{x[0]}</h3><p>{x[1]}</p></>}</article>)}</div></div></section>
 <section className="sec-guard" ref={g}><div data-reveal><article><strong>AI guardrails</strong><h2>Human review for sensitive workflows.</h2><p>Chatbots and AI agents handle routine replies, but anything involving money, cancellations, or ambiguous requests is routed to a person by design — not left to the model&apos;s best guess.</p></article><article><strong>Testing before launch</strong><h2>Real scenarios, not a demo script.</h2><p>Before anything goes live, we run it against real messages, edge cases, and failure paths — including what happens when an integration is slow or down.</p></article></div></section>
 <section className="sec-reliability" ref={r}><div><header data-reveal><h2>Reliability &amp; handoff.</h2></header><div className="sec-grid">{reliability.map((x,i)=><article className={i===2?'feature':''} data-reveal key={x[0]}>{i===2?<div className="sec-feature"><h3>{x[0]}</h3><p>{x[1]}</p></div>:<><h3>{x[0]}</h3><p>{x[1]}</p></>}</article>)}</div></div></section>
 <section className="sec-marquee" ref={m}><div><header data-reveal><strong>Integrations</strong><h2>Connected carefully, with scoped access.</h2><p>These are the platforms we connect to most — each with the minimum permissions the workflow needs, nothing more.</p></header><div className="sec-marquee-box"><ToolRow items={tools1}/><ToolRow items={tools2} reverse/><i/><i/></div></div></section>
 <section className="sec-faq" ref={f}><div><header data-reveal><span><CircleHelp size={13}/>FAQ</span><h2>Security Questions</h2><p>Have a question? We&apos;ve got answers. If you don&apos;t find what you&apos;re looking for, feel free to contact us.</p></header><div>{faqs.map((x,i)=>{const active=open===i;return <article className={active?'open':''} data-reveal key={x.q}><button aria-expanded={active} onClick={()=>setOpen(active?-1:i)}><span>{x.q}</span><ChevronDown size={20}/></button><div className="sec-answer"><div><p>{x.a}</p></div></div></article>})}</div></div></section>
 <section className="sec-cta" ref={c}><div className="sec-cta-wrap"><div className="sec-cta-panel" data-reveal><div className="sec-cta-copy"><strong>Have specific requirements?</strong><h2>Talk Through Your <span>Security Needs</span></h2><p>Tell us about your access, compliance, or review requirements on a free discovery call — we&apos;ll be upfront about what we can and can&apos;t do.</p><div>{['Free audit included','No long contracts','30-day support'].map(x=><span key={x}><b>✓</b>{x}</span>)}</div></div><div className="sec-cta-action"><strong>What you get in 30 minutes</strong><div>{['A map of your biggest time drains','Which workflow to automate first','A fixed quote — before we build anything'].map(x=><span key={x}><b>✓</b>{x}</span>)}</div><Link href="/contact" className="cta-sweep">Start With a Workflow Audit <img src="/assets/icon-arrow-right.svg" alt=""/></Link></div></div></div></section>
 <style>{`
 .security-approved,.security-approved *{box-sizing:border-box}.security-approved{overflow:hidden;background:#F7F2EA}.sec-hero{background:radial-gradient(1000px 600px at 78% -15%,rgba(23,160,99,.2),transparent 60%),#0A120E}.sec-hero>div{max-width:780px;margin:auto;padding:clamp(56px,8vw,88px) clamp(20px,3vw,32px) clamp(44px,6vw,64px);display:flex;flex-direction:column;align-items:center;gap:22px;text-align:center}.sec-badge{display:flex;align-items:center;gap:9px;padding:8px 16px;border:1px solid rgba(217,179,106,.4);border-radius:999px;background:rgba(217,179,106,.1);font:700 11.5px 'Instrument Sans';letter-spacing:.14em;color:#D9B36A;text-transform:uppercase;animation:v3Rise .65s var(--ease-premium) both}.sec-badge i{width:7px;height:7px;border-radius:50%;background:#D9B36A}.sec-hero h1{margin:0;font:600 clamp(34px,4.6vw,54px)/1.1 'Space Grotesk';color:#F5F0E8;letter-spacing:-.025em;animation:v3Rise .7s .08s var(--ease-premium) both}.sec-hero h1 span{color:#2BD483}.sec-hero p{max-width:560px;margin:0;font:400 18px/1.65 'Instrument Sans';color:rgba(245,240,232,.62);animation:v3Rise .7s .16s var(--ease-premium) both}
 .sec-access{background-color:#F7F2EA;background-image:radial-gradient(rgba(14,42,29,.06) 1px,transparent 1.5px);background-size:26px 26px}.sec-access>div,.sec-reliability>div{max-width:1180px;margin:auto;padding:clamp(56px,8vw,92px) clamp(20px,3vw,32px)}.sec-access header,.sec-reliability header{display:flex;flex-direction:column;align-items:center;gap:14px;margin-bottom:40px;text-align:center}.sec-access header>div{display:flex;align-items:center;gap:14px;font:700 12px 'Instrument Sans';letter-spacing:.18em;color:#128A54;text-transform:uppercase}.sec-access header i{width:38px;height:2px;background:#D9B36A}.sec-access h2,.sec-reliability h2{margin:0;font:600 clamp(28px,3.6vw,42px)/1.15 'Space Grotesk';color:#0A120E;letter-spacing:-.02em}.sec-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:20px}.sec-grid article{grid-column:span 3;padding:clamp(24px,2.6vw,30px);display:flex;flex-direction:column;gap:12px;background:linear-gradient(178deg,#fff,#FBF7EE 68%,#F6F1E4);border:1px solid rgba(13,58,49,.14);border-radius:20px;box-shadow:0 16px 40px rgba(18,32,27,.08)}.sec-grid article.feature{grid-column:span 6}.sec-feature{display:grid;grid-template-columns:minmax(0,.8fr) minmax(0,1.2fr);gap:clamp(16px,2.4vw,32px)}.sec-grid h3{margin:0;font:600 18px 'Space Grotesk';color:#0A120E}.sec-feature h3{font-size:clamp(20px,2.2vw,24px)}.sec-grid p{margin:0;font:400 14.5px/1.62 'Instrument Sans';color:#5B6355}.sec-feature p{font-size:15px;line-height:1.65}
 .sec-guard{background:#0E241A}.sec-guard>div{max-width:1100px;margin:auto;padding:clamp(56px,8vw,88px) clamp(20px,3vw,32px);display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:clamp(28px,4vw,48px)}.sec-guard article{display:flex;flex-direction:column;gap:14px}.sec-guard strong{font:700 11px 'Instrument Sans';letter-spacing:.16em;color:#2BD483;text-transform:uppercase}.sec-guard h2{margin:0;font:600 clamp(24px,2.8vw,32px)/1.2 'Space Grotesk';color:#F5F0E8}.sec-guard p{margin:0;font:400 15.5px/1.65 'Instrument Sans';color:rgba(245,240,232,.62)}.sec-reliability{background:#F7F2EA}
 .sec-marquee{background:#0E241A}.sec-marquee>div{max-width:1180px;margin:auto;padding:clamp(48px,6vw,76px) clamp(20px,3vw,32px);display:flex;flex-direction:column;gap:28px}.sec-marquee header{display:flex;flex-direction:column;align-items:center;gap:12px;text-align:center}.sec-marquee header strong{font:700 12px 'Instrument Sans';letter-spacing:.18em;color:#2BD483;text-transform:uppercase}.sec-marquee h2{margin:0;font:600 clamp(26px,3.2vw,38px)/1.15 'Space Grotesk';color:#F5F0E8}.sec-marquee header p{max-width:560px;margin:0;font:400 16px/1.6 'Instrument Sans';color:rgba(245,240,232,.6)}.sec-marquee-box{position:relative;overflow:hidden;display:flex;flex-direction:column;gap:14px}.sec-tool-row{display:flex;gap:12px;width:max-content;animation:secDriftL 38s linear infinite}.sec-tool-row.reverse{animation:secDriftR 44s linear infinite}.sec-tool-row:hover{animation-play-state:paused}.sec-tool{display:flex;align-items:center;gap:11px;padding:8px 20px 8px 9px;border-radius:999px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.12);white-space:nowrap;font:600 14px 'Instrument Sans';color:#F5F0E8}.sec-tool i{width:34px;height:34px;display:flex;align-items:center;justify-content:center;border-radius:9px;background:#F5F0E8}.sec-tool img{width:22px;height:22px}.sec-marquee-box>i{position:absolute;top:0;bottom:0;width:80px;pointer-events:none}.sec-marquee-box>i:first-of-type{left:0;background:linear-gradient(90deg,#0E241A,transparent)}.sec-marquee-box>i:last-of-type{right:0;background:linear-gradient(270deg,#0E241A,transparent)}@keyframes secDriftL{to{transform:translateX(-50%)}}@keyframes secDriftR{from{transform:translateX(-50%)}to{transform:translateX(0)}}
 .sec-faq{background:linear-gradient(180deg,#F7F2EA,#EFE7D6);border-top:1px solid #EDE6D8}.sec-faq>div{max-width:896px;margin:auto;padding:clamp(56px,8vw,96px) clamp(16px,3vw,32px)}.sec-faq header{display:flex;flex-direction:column;align-items:center;margin-bottom:clamp(44px,6vw,64px);text-align:center}.sec-faq header>span{display:flex;align-items:center;gap:5px;margin-bottom:16px;padding:4px 11px;border-radius:999px;background:#E8DFCC;font:600 12.5px 'Instrument Sans'}.sec-faq h2{margin:0 0 16px;font:700 clamp(30px,4vw,44px)/1.1 'Space Grotesk';color:#0A120E}.sec-faq header p{max-width:672px;margin:0;font:400 clamp(16px,1.6vw,18px)/1.6 'Instrument Sans';color:#68705F}.sec-faq>div>div{display:flex;flex-direction:column;gap:16px}.sec-faq article{overflow:hidden;background:#fff;border:1px solid #E8DFCC;border-radius:12px}.sec-faq article.open{border-color:rgba(23,160,99,.5);box-shadow:0 4px 6px -1px rgba(18,32,27,.1)}.sec-faq button{width:100%;display:flex;justify-content:space-between;align-items:center;gap:16px;padding:clamp(16px,2.4vw,24px);border:0;background:transparent;text-align:left;font:600 clamp(16px,1.7vw,18px) 'Space Grotesk';color:#0A120E}.sec-faq button svg{flex-shrink:0;color:#68705F;transition:.4s}.sec-faq .open button svg{transform:rotate(180deg)}.sec-answer{display:grid;grid-template-rows:0fr;opacity:0;transition:.45s}.sec-answer>div{overflow:hidden}.sec-answer p{margin:0;padding:clamp(16px,2.4vw,24px);border-top:1px solid #E8DFCC;font:400 clamp(14px,1.5vw,16px)/1.65 'Instrument Sans';color:#68705F}.sec-faq .open .sec-answer{grid-template-rows:1fr;opacity:1}
 .sec-cta{background:radial-gradient(760px 420px at 50% -15%,rgba(23,160,99,.18),transparent 62%),#0A120E}.sec-cta-wrap{max-width:1180px;margin:auto;padding:clamp(56px,8vw,96px) clamp(20px,3vw,32px)}.sec-cta-panel{max-width:1060px;margin:auto;padding:clamp(26px,4.5vw,54px);display:grid;grid-template-columns:minmax(0,1.1fr) minmax(0,.9fr);gap:clamp(28px,4vw,56px);align-items:center;background:linear-gradient(160deg,#10301F,#0A1C12);border:1px solid rgba(255,253,246,.14);border-radius:28px}.sec-cta-copy{display:flex;flex-direction:column;align-items:flex-start;gap:18px}.sec-cta-copy>strong{font:700 12px 'Instrument Sans';letter-spacing:.18em;color:#D9B36A;text-transform:uppercase}.sec-cta-copy h2{margin:0;font:600 clamp(30px,3.8vw,46px)/1.12 'Space Grotesk';color:#F5F0E8}.sec-cta-copy h2 span{white-space:nowrap}.sec-cta-copy p{max-width:440px;margin:0;font:400 17px/1.65 'Instrument Sans';color:rgba(245,240,232,.62)}.sec-cta-copy>div{display:flex;flex-wrap:wrap;gap:10px}.sec-cta-copy>div span{padding:9px 15px;border-radius:999px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.14);white-space:nowrap;font:600 13.5px 'Instrument Sans';color:rgba(245,240,232,.78)}.sec-cta-copy b,.sec-cta-action b{color:#2BD483;margin-right:8px}.sec-cta-action{padding:clamp(20px,2.6vw,30px);display:flex;flex-direction:column;gap:14px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.12);border-radius:20px}.sec-cta-action>strong{font:700 10.5px 'Instrument Sans';letter-spacing:.14em;color:rgba(245,240,232,.5);text-transform:uppercase}.sec-cta-action>div{display:flex;flex-direction:column;gap:11px}.sec-cta-action>div span{font:500 14.5px/1.5 'Instrument Sans';color:rgba(245,240,232,.8)}.sec-cta-action a{width:100%;display:flex;align-items:center;justify-content:center;gap:10px;padding:17px 20px;border-radius:13px;background:linear-gradient(160deg,#E7C57E,#D9B36A);white-space:nowrap;text-decoration:none;font:600 16px 'Instrument Sans';color:#0A120E}.sec-cta-action a img{width:15px;height:15px}
 @media(max-width:860px){.sec-cta-panel{grid-template-columns:1fr}}@media(max-width:820px){.sec-grid{grid-template-columns:1fr}.sec-grid article,.sec-grid article.feature{grid-column:auto!important}.sec-feature{grid-template-columns:1fr}}@media(max-width:640px){.sec-cta-panel{padding:24px 20px}.sec-cta-copy h2{font-size:29px}.sec-cta-action a{padding:16px 12px;font-size:14px}}html[data-motion='reduced'] .sec-tool-row{animation:none!important;transform:none!important}html[data-motion='reduced'] .sec-tool[data-marquee-sequence='duplicate']{display:none!important}@media(prefers-reduced-motion:reduce){html:not([data-motion='full']) .sec-tool-row{animation:none!important;transform:none!important}html:not([data-motion='full']) .sec-tool[data-marquee-sequence='duplicate']{display:none!important}}
 `}</style></div>}
