'use client'

import { useState, useCallback } from 'react'
import type { OnboardingFormData, ProposalOutput } from '@/lib/admin-types'
import { generateProposal } from '@/lib/proposal-generator'
import { ProposalSections } from './proposal-sections'
import { Loader2, RefreshCw, Copy, Printer, Send, ChevronDown, ChevronUp } from 'lucide-react'

export function ProposalOutputView({
  intakeData,
}: {
  intakeData: OnboardingFormData
}) {
  const [proposal, setProposal] = useState<ProposalOutput | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [showNotes, setShowNotes] = useState(false)
  const [copiedSection, setCopiedSection] = useState<string | null>(null)
  const [generated, setGenerated] = useState(false)

  const generate = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const result = await generateProposal(intakeData)
      setProposal(result)
      setGenerated(true)
      localStorage.setItem('co_last_proposal', JSON.stringify(result))
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate proposal')
    } finally {
      setLoading(false)
    }
  }, [intakeData])

  const copySection = useCallback((text: string) => {
    navigator.clipboard.writeText(text)
    setCopiedSection(text.slice(0, 30))
    setTimeout(() => setCopiedSection(null), 2000)
  }, [])

  const handlePrint = () => {
    window.print()
  }

  const handleSendEmail = () => {
    if (!proposal) return
    const subject = encodeURIComponent(
      `Proposal for ${intakeData.companyName} — CodeOutfitters`
    )
    const body = encodeURIComponent(
      [
        `Proposal for ${intakeData.companyName}`,
        '',
        `Executive Summary:`,
        proposal.executiveSummary,
        '',
        `Recommendation:`,
        proposal.recommendation,
        '',
        `Investment:`,
        proposal.investment,
        '',
        `---`,
        `Generated by CodeOutfitters Admin`,
      ].join('\n')
    )
    window.open(`mailto:${intakeData.email}?subject=${subject}&body=${body}`)
  }

  const handleCopyAll = () => {
    if (!proposal) return
    const text = [
      `EXECUTIVE SUMMARY\n${proposal.executiveSummary}`,
      `\nCHALLENGE\n${proposal.challenge}`,
      `\nRECOMMENDATION\n${proposal.recommendation}`,
      `\nIN PRACTICE\n${proposal.practicalLook}`,
      `\nTECHNICAL APPROACH\n${proposal.technicalApproach}`,
      `\nREQUIREMENTS\n${proposal.requirements.join('\n')}`,
      `\nTIMELINE\n${proposal.timeline.map((t) => `${t.week}: ${t.deliverable}`).join('\n')}`,
      `\nINVESTMENT\n${proposal.investment}`,
      `\nWHY US\n${proposal.whyUs.join('\n')}`,
      `\nNEXT STEPS\n${proposal.nextSteps.join('\n')}`,
      `\nFUTURE OPPORTUNITIES\n${proposal.futureOpportunities}`,
    ].join('\n\n')
    navigator.clipboard.writeText(text)
  }

  if (!generated && !loading && !error) {
    return (
      <div className="text-center py-20">
        <p className="text-white/60 text-sm mb-4">
          Ready to generate a proposal for {intakeData.companyName}?
        </p>
        <button onClick={generate} className="btn-primary text-sm py-3 px-6">
          Generate Proposal
        </button>
      </div>
    )
  }

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-20">
        <Loader2 className="w-8 h-8 text-[#C8A96E] animate-spin mb-4" />
        <p className="text-white/60 text-sm">Generating proposal with Claude...</p>
        <p className="text-white/40 text-xs mt-2">This takes about 15-30 seconds</p>
      </div>
    )
  }

  if (error) {
    return (
      <div className="text-center py-20">
        <div className="bg-red-500/10 border border-red-500/20 rounded-xl p-6 max-w-lg mx-auto mb-6">
          <p className="text-red-400 text-sm font-medium mb-1">Error</p>
          <p className="text-white/60 text-sm">{error}</p>
        </div>
        <button onClick={generate} className="btn-primary text-sm py-3 px-6">
          Try Again
        </button>
      </div>
    )
  }

  if (!proposal) return null

  return (
    <div className="max-w-4xl mx-auto px-5 sm:px-6 lg:px-8 py-10">
      {/* Action bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 mb-8 print:hidden">
        <div>
          <h1 className="font-heading text-xl font-bold text-white tracking-tight">
            {intakeData.companyName} — Proposal
          </h1>
          <p className="text-white/40 text-xs mt-1">
            Generated {new Date().toLocaleDateString()} for {intakeData.fullName}
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <button
            onClick={generate}
            className="flex items-center gap-1.5 bg-white/10 hover:bg-white/15 text-white text-xs font-medium px-3 py-2 rounded-lg transition-colors"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            Regenerate
          </button>
          <button
            onClick={handleCopyAll}
            className="flex items-center gap-1.5 bg-white/10 hover:bg-white/15 text-white text-xs font-medium px-3 py-2 rounded-lg transition-colors"
          >
            <Copy className="w-3.5 h-3.5" />
            Copy All
          </button>
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 bg-white/10 hover:bg-white/15 text-white text-xs font-medium px-3 py-2 rounded-lg transition-colors"
          >
            <Printer className="w-3.5 h-3.5" />
            Print / PDF
          </button>
          <button
            onClick={handleSendEmail}
            className="flex items-center gap-1.5 bg-[#2A6B5A] hover:bg-[#1A4A3B] text-white text-xs font-medium px-3 py-2 rounded-lg transition-colors"
          >
            <Send className="w-3.5 h-3.5" />
            Send to Client
          </button>
        </div>
      </div>

      {/* Internal notes — collapsible, hidden in print */}
      <div className="mb-8 border border-[#C8A96E]/30 rounded-xl overflow-hidden print:hidden">
        <button
          onClick={() => setShowNotes(!showNotes)}
          className="w-full flex items-center justify-between px-5 py-3 bg-[#C8A96E]/10 text-left"
        >
          <span className="text-xs font-semibold text-[#C8A96E] uppercase tracking-wide">
            Tayyab&apos;s Internal Notes
          </span>
          {showNotes ? (
            <ChevronUp className="w-4 h-4 text-[#C8A96E]" />
          ) : (
            <ChevronDown className="w-4 h-4 text-[#C8A96E]" />
          )}
        </button>
        {showNotes && (
          <div className="px-5 py-4 space-y-3 text-sm text-white/70">
            <div>
              <span className="text-xs text-white/40 uppercase tracking-wide">Fit:</span>{' '}
              {intakeData.fitAssessment}
            </div>
            {intakeData.redFlags && (
              <div>
                <span className="text-xs text-white/40 uppercase tracking-wide">Red Flags:</span>{' '}
                {intakeData.redFlags}
              </div>
            )}
            <div>
              <span className="text-xs text-white/40 uppercase tracking-wide">Lead With:</span>{' '}
              {intakeData.strongestPainPoint}
            </div>
            <div>
              <span className="text-xs text-white/40 uppercase tracking-wide">Pitch:</span>{' '}
              {intakeData.recommendedAutomation}
            </div>
            <div>
              <span className="text-xs text-white/40 uppercase tracking-wide">Effort:</span>{' '}
              {intakeData.estimatedEffort}
            </div>
          </div>
        )}
      </div>

      {/* Copied toast */}
      {copiedSection && (
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 bg-[#1C1612] text-white text-xs px-4 py-2 rounded-lg shadow-lg border border-white/10 z-50">
          Copied!
        </div>
      )}

      {/* Print-only header */}
      <div className="hidden print:block mb-8">
        <h1 className="text-2xl font-bold text-[#1C1612]">
          Proposal for {intakeData.companyName}
        </h1>
        <p className="text-sm text-[#6B6155]">
          Prepared by CodeOutfitters &middot; {new Date().toLocaleDateString()}
        </p>
      </div>

      {/* Proposal sections */}
      <ProposalSections proposal={proposal} onCopySection={copySection} />
    </div>
  )
}
